### ISSUE TITLE
script.py exits wiht excpetion

### ISSUE THREAD

**Issue by ajesaramos** [Trenblack/Sad_Boy_Bot#4]
Hi I saw your video and wanted to try your implementation of moviepy but I got an error message. I don't quite know what is wrong. Could you throw me a hand to solve it?

Error message:

Filename of Movie?stronger.mp4
Filename of music?highest.mp3
Desired edit duration in seconds?44
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/moviepy/video/VideoClip.py", line 1137, in __init__
    subprocess_call(cmd, logger=None)
  File "/usr/local/lib/python3.10/dist-packages/moviepy/tools.py", line 54, in subprocess_call
    raise IOError(err.decode('utf8'))
OSError: convert-im6.q16: attempt to perform an operation not allowed by the security policy `@/tmp/tmp_wl2qwft.txt' @ error/property.c/InterpretImageProperties/3706.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dropout/Desktop/Sad Boy Project/script.py", line 53, in <module>
    g.create(desired_duration)
  File "/home/dropout/Desktop/Sad Boy Project/script.py", line 21, in create
    self.random_word_screen()
  File "/home/dropout/Desktop/Sad Boy Project/script.py", line 44, in random_word_screen
    clip = mpe.TextClip(spaced_word, fontsize = 70, color = 'white',size=self.clip.size,bg_color = 'black',method='caption',align='center').set_duration(2)
  File "/usr/local/lib/python3.10/dist-packages/moviepy/video/VideoClip.py", line 1146, in __init__
    raise IOError(error)
OSError: MoviePy Error: creation of None failed because of the following error:

convert-im6.q16: attempt to perform an operation not allowed by the security policy `@/tmp/tmp_wl2qwft.txt' @ error/property.c/InterpretImageProperties/3706.
.

.This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect

I am using Kali Linux and as far as I know imagemagick is installed at least as an executable

I would appreciate your help on this

**Comment by Trenblack** [comment]
Try running !apt install imagemagick, and make sure you're specifying the path correctly

**Comment by ajesaramos** [comment]
Hi Trenblack!,

Thanks for your reply. Sorry for the delay it was national holiday over here. I tried !apt install imagemagick and apparently the command ran but without output. A detail to be mentioned is that the command line insisted in correctin !apt to !aptitude. Since posting this issue I managed to get past the mentioned error by following the suggestions given [here:](https://stackoverflow.com/questions/50602024/error-while-loading-shared-libraries-libmagickcore-7-q16hdri-so-6)

[](https://stackoverflow.com/questions/50602024/error-while-loading-shared-libraries-libmagickcore-7-q16hdri-so-6)

But now I'm faced with the following error message:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/moviepy/video/VideoClip.py", line 1137, in __init__
    subprocess_call(cmd, logger=None)
  File "/usr/local/lib/python3.10/dist-packages/moviepy/tools.py", line 54, in subprocess_call
    raise IOError(err.decode('utf8'))
OSError: convert: delegate library support not built-in '/usr/share/fonts/type1/gsfonts/n022003l.pfb' (Freetype) @ warning/annotate.c/RenderFreetype/2064.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/741.
convert: delegate library support not built-in '/usr/share/fonts/type1/gsfonts/n022003l.pfb' (Freetype) @ warning/annotate.c/RenderFreetype/2064.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/741.
convert: delegate library support not built-in '/usr/share/fonts/type1/gsfonts/n022003l.pfb' (Freetype) @ warning/annotate.c/RenderFreetype/2064.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/741.
convert: no images defined `PNG32:/tmp/tmpyuqnde6r.png' @ error/convert.c/ConvertImageCommand/3342.

I read something about Freetype not being included in the makefile and being needed for texts, and to include it in the file and run it again but honestly I don't know how that is done.

[UPDATE]
I read [here](https://github.com/serverlesspub/imagemagick-aws-lambda-2/issues/6) to download the imagemagick zip file provided by thecfguy and use it, and am thinking of using the makefile provided by trungegd. It may get solved on its own upon doing one of these but my question is if this should fix it or shall I do something else.

Could you help me with this?

Thanks a lot

**Comment by ajesaramos** [comment]
Hi,

I would like to provide a solution to my own issue.

The answer provided [here](https://askubuntu.com/questions/1042436/how-to-install-delegate-libraries-for-image-magick-7-0-7) by Andrew.46 should fix the problem if you are having trouble with imagemagick and freetype, namely:

> 
> OSError: convert: delegate library support not built-in '/usr/share/fonts/type1/gsfonts/n022003l.pfb' (Freetype) @ warning/annotate.c/RenderFreetype/2064.
> convert: no decode delegate for this image format ' @ error/constitute.c/ReadImage/741. convert: delegate library support not built-in '/usr/share/fonts/type1/gsfonts/n022003l.pfb' (Freetype) @ warning/annotate.c/RenderFreetype/2064. convert: no decode delegate for this image format ' @ error/constitute.c/ReadImage/741.
> convert: delegate library support not built-in '/usr/share/fonts/type1/gsfonts/n022003l.pfb' (Freetype) @ warning/annotate.c/RenderFreetype/2064.

Specifically the last apt-get from point 1 (on its own) and re-running make with additional options as stated in point 2 (Andrew.46's answer). No uninstalling was required for the fix.
